/**
 * /.netlify/functions/discovery
 *
 *   POST  { answers, website_hp, draftKey? }          submit -> GHL, returns the fit verdict
 *   POST  { draft: true, answers, step, draftKey? }   save a draft for another device
 *   GET   ?draft=<key>                                read a draft back
 *   GET   [?deep=1]                                   health (the Health Monitor reads this)
 *
 * Same delivery contract as build-brief.js, for the same reason: this form owns
 * delivery. `{ ok: true }` is returned ONLY after GHL has confirmed the write, and the
 * browser clears its saved copy only on that. The verdict rides back on the same
 * response, so a prospect is never shown a verdict for answers that were not stored.
 *
 * What this form deliberately does NOT do:
 *   - no phone field, so no A2P surface and no consent block (same call as /start/)
 *   - no message is ever sent to the prospect from here (the PIT has no messaging
 *     scope, by standard). The alert to Gus is a TASK on the contact.
 *   - a draft never notifies anyone. The page promises nothing is sent until submit.
 *
 * Environment: GHL_PIT (Netlify UI, never the repo). Needs contacts.write.
 * Field ids come from src/_data/discoveryFields.json, generated by
 * scripts/sync-discovery.mjs. Never type one.
 */
import { getStore } from "@netlify/blobs";
import { randomUUID } from "node:crypto";
import bank from "../../src/_data/discovery.json" with { type: "json" };
import fieldMap from "../../src/_data/discoveryFields.json" with { type: "json" };
import { verdict, verdictText, cardText, sharedFieldValues } from "./discovery-verdict.mjs";

const LOCATION_ID = fieldMap.locationId;
const GHL = "https://services.leadconnectorhq.com";
const ASSIGNEE_USER_ID = "0qYqX1PQslaWmsCvbJnY"; // Gus. Same constant as build-brief.js; not a secret.
const HEALTH_CACHE_MS = 10 * 60 * 1000;
const DRAFT_MAX_BYTES = 64 * 1024;
const DRAFT_MAX_AGE_MS = 90 * 24 * 60 * 60 * 1000;
const KEY_RE = /^[a-f0-9]{32}$/;
const CAP = { text: 300, email: 200, number: 20, longtext: 3000, own: 1500 };

const QUESTIONS = bank.steps.flatMap((s) => s.questions).filter((q) => q.kind !== "note");
const REQUIRED = QUESTIONS.filter((q) => q.required);

const json = (status, body) =>
  new Response(JSON.stringify(body), { status, headers: { "Content-Type": "application/json", "Cache-Control": "no-store" } });

const ghlHeaders = (token) => ({ Authorization: `Bearer ${token}`, Version: "2021-07-28", "Content-Type": "application/json" });

const str = (v, max) => (typeof v === "string" ? v : v == null ? "" : String(v)).trim().slice(0, max);

/**
 * Rebuild the answers from the question bank rather than trusting the payload's shape.
 * A tap can only be one of that question's real options, so a crafted request cannot
 * put arbitrary text into a field that reads as "they tapped this". Free text is capped.
 */
export function sanitize(raw = {}) {
  const a = {};
  for (const q of QUESTIONS) {
    const v = raw[q.id];
    if (q.kind === "multi") {
      const list = (Array.isArray(v) ? v : v ? [v] : []).filter((x) => q.options.includes(x));
      if (list.length) a[q.id] = q.max ? list.slice(0, q.max) : list;
    } else if (q.kind === "chips") {
      if (q.options.includes(v)) a[q.id] = v;
    } else {
      const s = str(v, CAP[q.kind] || CAP.text);
      if (s) a[q.id] = s;
    }
    if (q.own) {
      const own = str(raw[`${q.id}__own`], CAP.own);
      if (own) a[`${q.id}__own`] = own;
    }
  }
  return a;
}

async function health(req, token) {
  const out = {
    ok: !!token,
    service: "discovery",
    credential: token ? "configured" : "missing",
    fieldsLocal: Object.keys(fieldMap.fields).length,
    questions: QUESTIONS.length,
    checkedAt: new Date().toISOString(),
  };
  if (new URL(req.url).searchParams.get("deep") === "1" && token) {
    let store = null, cached = null;
    try { store = getStore("discovery-health"); cached = await store.get("deep", { type: "json" }); } catch {}
    if (cached && Date.now() - Date.parse(cached.checkedAt) < HEALTH_CACHE_MS) {
      out.deep = { ...cached, cached: true };
    } else {
      const d = { checkedAt: new Date().toISOString(), ghlAuth: "unknown", missingIds: [] };
      try {
        const res = await fetch(`${GHL}/locations/${LOCATION_ID}/customFields`, { headers: ghlHeaders(token) });
        if (res.ok) {
          const live = new Set(((await res.json()).customFields || []).map((f) => f.id));
          d.ghlAuth = "ok";
          d.missingIds = Object.entries(fieldMap.fields).filter(([, f]) => !live.has(f.id)).map(([k]) => k);
        } else {
          d.ghlAuth = res.status === 401 || res.status === 403 ? "rejected" : `http_${res.status}`;
        }
      } catch { d.ghlAuth = "unreachable"; }
      if (store) { try { await store.setJSON("deep", d); } catch {} }
      out.deep = d;
    }
    if (out.deep.ghlAuth !== "ok" || out.deep.missingIds.length) out.ok = false;
  }
  return json(out.ok ? 200 : 503, out);
}

async function readDraft(key) {
  if (!KEY_RE.test(key)) return json(400, { ok: false, error: "That link doesn't look right." });
  try {
    const store = getStore("discovery-drafts");
    const d = await store.get(key, { type: "json" });
    if (!d) return json(404, { ok: false, error: "Nothing is saved under that link. It may have been sent already." });
    if (Date.now() - Date.parse(d.savedAt) > DRAFT_MAX_AGE_MS) {
      try { await store.delete(key); } catch {}
      return json(404, { ok: false, error: "That saved copy was more than 90 days old and has been cleared." });
    }
    return json(200, { ok: true, step: d.step || 1, answers: d.answers || {} });
  } catch (e) {
    console.error("draft read failed:", e && e.message);
    return json(502, { ok: false, error: "The saved copy could not be read just now. Try again in a moment." });
  }
}

async function saveDraft(payload) {
  const answers = sanitize(payload.answers);
  const key = KEY_RE.test(payload.draftKey || "") ? payload.draftKey : randomUUID().replace(/-/g, "");
  const body = JSON.stringify({ savedAt: new Date().toISOString(), step: Number(payload.step) || 1, answers });
  if (Buffer.byteLength(body) > DRAFT_MAX_BYTES) return json(413, { ok: false, error: "That's more than this form can hold in a saved copy." });
  try {
    await getStore("discovery-drafts").set(key, body);
    return json(200, { ok: true, draftKey: key });
  } catch (e) {
    console.error("draft save failed:", e && e.message);
    return json(502, { ok: false, error: "The link could not be created just now. Your answers are still saved on this device." });
  }
}

export default async (req) => {
  const token = (process.env.GHL_PIT || "").trim();

  if (req.method === "GET") {
    const draft = new URL(req.url).searchParams.get("draft");
    return draft ? readDraft(draft) : health(req, token);
  }
  if (req.method !== "POST") return json(405, { ok: false, error: "Method not allowed." });

  let payload;
  try { payload = await req.json(); } catch { return json(400, { ok: false, error: "That submission could not be read." }); }

  // Honeypot: a real person never fills a field they cannot see.
  if (str(payload.website_hp, 50)) {
    console.log("honeypot tripped, dropping silently");
    return json(200, { ok: true, note: "ignored" });
  }

  if (payload.draft === true) return saveDraft(payload);

  if (!token) {
    console.error("GHL_PIT is not set on this deploy.");
    return json(500, { ok: false, code: "no_token", error: "This form is not finished being set up (no credential configured). Please email admin@406frontdesk.com. Nothing you typed is lost." });
  }

  const a = sanitize(payload.answers);
  const missing = REQUIRED.filter((q) => !a[q.id]).map((q) => q.label.toLowerCase());
  if (a.email && !/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(a.email)) missing.push("a valid email");
  if (missing.length) return json(400, { ok: false, error: `Still needed on step 1: ${missing.join(", ")}.` });

  const v = verdict(a);
  const vText = verdictText(v);
  const card = cardText(bank, a);

  const customFields = [];
  const push = (key, value) => {
    const f = fieldMap.fields[key];
    if (f && value) customFields.push({ id: f.id, field_value: value });
  };
  for (const [key, value] of Object.entries(sharedFieldValues(bank, a))) push(key, value);
  push("discovery_answer_card", card);
  push("discovery_fit_verdict", vText);

  const parts = a.full_name.split(/\s+/);
  const body = {
    locationId: LOCATION_ID,
    firstName: parts[0],
    lastName: parts.slice(1).join(" ") || parts[0],
    name: a.full_name,
    email: a.email,
    companyName: a.business,
    source: "Front Desk Discovery (406frontdesk.com)",
    tags: ["front desk discovery"],
    customFields,
  };

  let res, text;
  try {
    res = await fetch(`${GHL}/contacts/upsert`, { method: "POST", headers: ghlHeaders(token), body: JSON.stringify(body) });
    text = await res.text();
  } catch (e) {
    console.error("GHL request failed:", e && e.message);
    return json(502, { ok: false, error: "I could not reach the system that stores your answers. Nothing was saved. Please try again in a moment." });
  }
  if (!res.ok) {
    console.error(`GHL upsert failed ${res.status} :: ${text.slice(0, 500)}`);
    if (res.status === 401 || res.status === 403) {
      return json(502, { ok: false, code: "auth_rejected", upstream: res.status, error: "This form's credential was rejected by my CRM. Please email admin@406frontdesk.com. Nothing you typed is lost." });
    }
    return json(502, { ok: false, error: "Your answers could not be saved. Nothing was lost. Please try again, or email admin@406frontdesk.com." });
  }

  let contactId = null;
  try { contactId = (JSON.parse(text).contact || {}).id || null; } catch {}

  // THE ALERT IS A TASK. Best-effort after the confirmed write; never client-facing.
  let taskMade = false;
  if (contactId) {
    try {
      const t = await fetch(`${GHL}/contacts/${contactId}/tasks`, {
        method: "POST",
        headers: ghlHeaders(token),
        body: JSON.stringify({
          title: `Discovery in: ${a.business} (${v.level} fit)`,
          body: `Their one thing: "${a.headline}"\n\n${vText}\n\nFull answers are in the "Discovery answer card" field on this contact, and in the archive: node scripts/get-discovery-submission.mjs. Next: /discovery ${a.business} --report.`,
          dueDate: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
          completed: false,
          assignedTo: ASSIGNEE_USER_ID,
        }),
      });
      taskMade = t.ok;
      if (!t.ok) console.error(`task failed: ${t.status} ${(await t.text()).slice(0, 200)}`);
    } catch (e) { console.error("task failed:", e && e.message); }
  }

  // Immutable record. The endpoint UPSERTS, so a second submission overwrites the
  // contact's fields; this is the only place the first answers survive.
  try {
    const stamp = new Date().toISOString().replace(/[:.]/g, "-");
    await getStore("discovery-submissions").set(
      `${stamp}-${a.email.replace(/[^a-z0-9]+/gi, "-")}.json`,
      JSON.stringify({ receivedAt: new Date().toISOString(), contactId, answers: a, verdict: v, verdictText: vText, card, taskCreated: taskMade }, null, 2),
      { metadata: { email: a.email, contactId: contactId || "", business: a.business } }
    );
  } catch (e) {
    console.error("submission archive failed (contact was still saved):", e && e.message);
  }

  // The draft has done its job. Leaving it would keep a copy of their answers behind a
  // link they may have texted around.
  if (KEY_RE.test(payload.draftKey || "")) {
    try { await getStore("discovery-drafts").delete(payload.draftKey); } catch {}
  }

  console.log(`discovery stored for ${a.email}${contactId ? ` (contact ${contactId})` : ""}, ${customFields.length} fields, fit=${v.level}, task=${taskMade}`);
  return json(200, { ok: true, verdict: v, firstName: parts[0] });
};
