"""Self-host the Design Directions webfonts.

Fetches the SUBSET woff2 files behind the generated Google Fonts request, stores them
in src/assets/fonts/directions/, and writes src/css/directions-fonts.css with local
@font-face rules.

WHY: 406 grades other people's sites on third-party hosts and page speed in
/site-audit. Loading 34 families from fonts.gstatic.com on our own page is a
self-inflicted ding. Subsetting already cut the payload; this removes the third-party
request as well.

Licensing: every family here ships under the SIL Open Font License 1.1 or Apache 2.0,
both of which permit self-hosting and redistribution. A NOTICE file is written next to
the fonts recording that.
"""
import json, io, os, re, sys, hashlib, shutil, urllib.request

REPO = r"C:/Users/ghill/Documents/406-frontdesk-site"
FONT_DIR = os.path.join(REPO, "src/assets/fonts/directions")
CSS_OUT = os.path.join(REPO, "src/css/directions-fonts.css")

# A modern-Chrome UA is what makes the API return woff2 rather than ttf.
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36")


def get(url, binary=False):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as r:
        return r.read() if binary else r.read().decode("utf-8")


data = json.load(io.open(os.path.join(REPO, "src/_data/directions.json"), encoding="utf-8"))
src_url = data["googleFonts"]

print("fetching font CSS ...")
css = get(src_url)

# Parse @font-face blocks: family, weight, style, and the woff2 source.
blocks = re.findall(r"@font-face\s*\{(.*?)\}", css, re.S)
faces = []
for b in blocks:
    fam = re.search(r"font-family:\s*'([^']+)'", b)
    wgt = re.search(r"font-weight:\s*([0-9 ]+)", b)
    sty = re.search(r"font-style:\s*(\w+)", b)
    # subset faces are served from /l/font?kit=... with no .woff2 extension;
    # the format is declared separately, so match the URL and require that.
    url = re.search(r"url\((https://[^)]+)\)\s*format\('woff2'\)", b)
    if not (fam and url):
        continue
    stretch = re.search(r"font-stretch:\s*([^;]+);", b)
    urange = re.search(r"unicode-range:\s*([^;]+);", b)
    faces.append({
        "family": fam.group(1),
        "weight": (wgt.group(1).strip() if wgt else "400"),
        "style": (sty.group(1) if sty else "normal"),
        "stretch": (stretch.group(1).strip() if stretch else None),
        "range": (urange.group(1).strip() if urange else None),
        "url": url.group(1),
    })

if not faces:
    sys.exit("no @font-face blocks parsed - refusing to write a stylesheet that would "
             "silently fall back to system fonts")

# Wipe first: the files are generated and content-hashed, so stale hashes would
# otherwise pile up invisibly and get shipped.
if os.path.isdir(FONT_DIR):
    shutil.rmtree(FONT_DIR)
os.makedirs(FONT_DIR, exist_ok=True)
total = 0
lines = [
    "/* Design Directions - self-hosted webfonts.",
    " *",
    " * GENERATED by scripts/selfhost-fonts (do not hand-edit). The faces and the glyph",
    " * subset are derived from src/_data/directions.json; regenerate after changing the",
    " * sample copy, adding a direction, or changing a type pairing.",
    " *",
    " * Verified by: node scripts/check-directions.mjs",
    " * Source request (for reproducibility):",
    " *   " + src_url[:150] + ("..." if len(src_url) > 150 else ""),
    " *",
    " * Licences: SIL Open Font License 1.1 / Apache 2.0 - both permit self-hosting.",
    " *           See assets/fonts/directions/NOTICE.txt",
    " */",
    "",
]

seen = set()
by_digest = {}   # content hash -> filename, so identical variable faces are stored once
for f in faces:
    slug = re.sub(r"[^a-z0-9]+", "-", f["family"].lower()).strip("-")
    stem = "%s-%s%s" % (slug, f["weight"].replace(" ", "-"),
                        "" if f["style"] == "normal" else "-" + f["style"])
    if stem in seen:
        continue
    seen.add(stem)
    blob = get(f["url"], binary=True)
    # Netlify serves /assets/* as `immutable, max-age=1y`. The subset CHANGES whenever
    # the sample copy or the direction list changes, so the filename has to change with
    # it -- otherwise a returning visitor is pinned to a stale face for a year.
    digest = hashlib.sha256(blob).hexdigest()[:8]

    # Most of these are VARIABLE fonts: Google returns one identical file for 400 and
    # 600. Writing it twice would ship the bytes twice AND make the browser fetch the
    # same face under two URLs. Key on content, and let both @font-face rules point at
    # the one file.
    if digest in by_digest:
        name = by_digest[digest]
    else:
        name = "%s-%s.woff2" % (stem, digest)
        by_digest[digest] = name
        path = os.path.join(FONT_DIR, name)
        tmp = path + ".tmp"
        with open(tmp, "wb") as fh:
            fh.write(blob)
        os.replace(tmp, path)
        total += len(blob)
    lines += [
        "@font-face {",
        "  font-family: '%s';" % f["family"],
        "  font-style: %s;" % f["style"],
        "  font-weight: %s;" % f["weight"],
        "  font-display: swap;",
    ]
    if f["stretch"]:
        lines.append("  font-stretch: %s;" % f["stretch"])
    lines.append("  src: url('/assets/fonts/directions/%s') format('woff2');" % name)
    # Carried through deliberately: these are SUBSET faces, so a glyph outside the
    # range must fall back to the system font rather than render as tofu.
    if f["range"]:
        lines.append("  unicode-range: %s;" % f["range"])
    lines.append("}")

io.open(CSS_OUT + ".tmp", "w", encoding="utf-8", newline="\n").write("\n".join(lines) + "\n")
os.replace(CSS_OUT + ".tmp", CSS_OUT)

notice = os.path.join(FONT_DIR, "NOTICE.txt")
io.open(notice + ".tmp", "w", encoding="utf-8", newline="\n").write(
    "Webfonts used by /design-directions/.\n\n"
    "Retrieved from Google Fonts and subset to the glyphs the page renders.\n"
    "Every family here is licensed under either the SIL Open Font License 1.1\n"
    "or the Apache License 2.0. Both permit self-hosting and redistribution.\n\n"
    "Full licence text for each family: https://fonts.google.com/\n\n"
    "Files are GENERATED. Regenerate with scripts/selfhost-fonts rather than\n"
    "editing or adding files by hand; scripts/check-directions.mjs verifies that\n"
    "every face the data needs is present here.\n")
os.replace(notice + ".tmp", notice)

print("faces declared: %d" % len(seen))
print("files written : %d (deduped by content)" % len(by_digest))
print("total size    : %.0f KB" % (total / 1024))
print("css           : %s" % os.path.relpath(CSS_OUT, REPO))
